# Generated by Django 2.2.6 on 2020-01-23 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('send_price', models.IntegerField(null=True)),
                ('factor_id', models.IntegerField()),
                ('factor_address', models.CharField(max_length=250, null=True)),
                ('factor_date', models.DateTimeField(null=True)),
                ('prepayment', models.IntegerField()),
                ('factor_pay', models.BooleanField(null=True)),
                ('Delivery_time', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.Item')),
            ],
        ),
    ]
