# Generated by Django 2.2.6 on 2020-01-21 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_choice', models.CharField(choices=[('Tehran', 'tehran'), ('Soon', 'soon')], max_length=250, null=True)),
                ('city_choice', models.CharField(choices=[('Tehran', 'tehran'), ('Soon', 'soon')], max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('post_code', models.IntegerField(default=None, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone_numb', models.TextField(default=None, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersAuth.UserAddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.CharField(blank=True, max_length=250, null=True)),
                ('send_price', models.IntegerField(null=True)),
                ('factor_id', models.IntegerField()),
                ('factor_item', models.CharField(max_length=250, null=True)),
                ('factor_date', models.DateField(null=True)),
                ('factor_pay', models.BooleanField(null=True)),
                ('Delivery', models.BooleanField(null=True)),
                ('factor_price', models.IntegerField()),
                ('Delivery_time', models.DateTimeField()),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.Item')),
            ],
        ),
    ]
