# Generated by Django 2.2.6 on 2020-01-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Laptop', 'laptop'), ('Mobile', 'mobile'), ('Home', 'home')], default='home', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('kinds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_status', models.CharField(blank=True, choices=[('None', 'none'), ('Andriod', 'andriod'), ('IOS', 'ios'), ('Windsows Phone', 'windsowsphone'), ('Symbian ', 'symbian '), ('Black Berry', 'blackberry'), ('KaiOS ', 'kaios')], default='home', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('made', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(null=True)),
                ('model', models.DateField(null=True)),
                ('dateadd', models.DateField(blank=True, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.Item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0, help_text='10 character', unique=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('lcd', models.CharField(max_length=250, null=True)),
                ('original', models.BooleanField(default='original', null=True)),
                ('camera', models.CharField(max_length=250, null=True)),
                ('ram', models.CharField(max_length=250, null=True)),
                ('cpu', models.CharField(max_length=250, null=True)),
                ('memory', models.CharField(max_length=250, null=True)),
                ('sizelcd', models.CharField(max_length=250, null=True)),
                ('touchlcd', models.BooleanField(default='Yes', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Content/static/images')),
                ('details', models.TextField(blank=True, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.MobileItem')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_status', models.CharField(choices=[('NoteBook', 'notebook'), ('UltraBook', 'ultrabook'), ('NetBook', 'netbook'), ('ChromeBook', 'chromebook')], default='notebook', max_length=20)),
                ('brand', models.CharField(max_length=250, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(null=True)),
                ('made', models.CharField(blank=True, max_length=250, null=True)),
                ('dateadd', models.DateField(null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.Item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0, help_text='10 character', unique=True)),
                ('model', models.DateField(blank=True, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('original', models.BooleanField(default='original', null=True)),
                ('ram', models.CharField(max_length=200, null=True)),
                ('graphic', models.CharField(max_length=200, null=True)),
                ('cpu', models.CharField(max_length=200, null=True)),
                ('cpu_status', models.CharField(choices=[('DualCore', 'dualcore'), ('QualCore', 'qualcore'), ('CoreI3', 'corei3'), ('CoreI5', 'corei5'), ('CoreI7', 'corei7'), ('CoreI9', 'corei9'), ('Xeon', 'xeon'), ('Ryzen3', 'ryzen3'), ('Ryzen5', 'ryzen5'), ('Ryzen7', 'ryzen7'), ('Tegra K1', 'tegrak1')], default='home', max_length=20)),
                ('hdd', models.CharField(max_length=200, null=True)),
                ('os_statuse', models.CharField(choices=[('Windows', 'windows'), ('Linux', 'qualcore'), ('Mac', 'mac'), ('Google Chrome', 'googlechrome'), ('Windows7', 'windows7'), ('Windows8', 'windows8'), ('Windows9', 'windows9'), ('Windows19', 'windows10')], default='windows', max_length=20)),
                ('size_status', models.CharField(choices=[('10', '10'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('17', '17'), ('19', '19')], max_length=20)),
                ('touchlcd', models.BooleanField(default='No', null=True)),
                ('opaquelcd', models.BooleanField(default='Yes', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Content/static/images')),
                ('details', models.TextField(blank=True, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.LaptopItem')),
            ],
        ),
        migrations.CreateModel(
            name='HomeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0, help_text='10 character', unique=True)),
                ('kind_status', models.CharField(blank=True, choices=[('Digital', 'dogotal'), ('Kitchen', 'kitchen'), ('Other', 'other')], default='home', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('made', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(null=True)),
                ('model', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('original', models.BooleanField(blank=True, default='original', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Content/static/images')),
                ('details', models.TextField(blank=True, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.Item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
